{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "27b9999d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting faiss-cpu\n",
      "  Downloading faiss_cpu-1.11.0.post1-cp313-cp313-macosx_14_0_arm64.whl.metadata (5.0 kB)\n",
      "Requirement already satisfied: numpy<3.0,>=1.25.0 in /Users/prahlad/Desktop/Projects/mechagent_prahlad/mecagent-technical-test/x3D/genx3denv/lib/python3.13/site-packages (from faiss-cpu) (2.3.1)\n",
      "Requirement already satisfied: packaging in /Users/prahlad/Desktop/Projects/mechagent_prahlad/mecagent-technical-test/x3D/genx3denv/lib/python3.13/site-packages (from faiss-cpu) (24.2)\n",
      "Downloading faiss_cpu-1.11.0.post1-cp313-cp313-macosx_14_0_arm64.whl (3.3 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.3/3.3 MB\u001b[0m \u001b[31m678.1 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: faiss-cpu\n",
      "Successfully installed faiss-cpu-1.11.0.post1\n"
     ]
    }
   ],
   "source": [
    "!pip install faiss-cpu"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "4f873df1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/prahlad/Desktop/Projects/mechagent_prahlad/mecagent-technical-test/x3D/genx3denv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "Batches:   0%|          | 0/109 [00:00<?, ?it/s]/Users/prahlad/Desktop/Projects/mechagent_prahlad/mecagent-technical-test/x3D/genx3denv/lib/python3.13/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.\n",
      "  return forward_call(*args, **kwargs)\n",
      "Batches: 100%|██████████| 109/109 [00:06<00:00, 16.26it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔎 Vector DB created with 3480 entries.\n",
      "✅ Vector index and data saved.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import pandas as pd\n",
    "from sentence_transformers import SentenceTransformer\n",
    "import faiss\n",
    "import numpy as np\n",
    "import pickle\n",
    "\n",
    "# Load data\n",
    "jsonl_file = \"rag_dataset_local.jsonl\"\n",
    "data = []\n",
    "with open(jsonl_file, \"r\", encoding=\"utf-8\") as f:\n",
    "    for line in f:\n",
    "        data.append(json.loads(line))\n",
    "df = pd.DataFrame(data)\n",
    "\n",
    "# Load embedding model\n",
    "model = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
    "\n",
    "# Embed the prompt field\n",
    "texts = df[\"prompt\"].tolist()\n",
    "embeddings = model.encode(texts, show_progress_bar=True)\n",
    "\n",
    "# Convert to numpy array\n",
    "embeddings = np.array(embeddings).astype(\"float32\")\n",
    "\n",
    "# Create FAISS index\n",
    "index = faiss.IndexFlatL2(embeddings.shape[1])  # L2 distance\n",
    "index.add(embeddings)\n",
    "\n",
    "print(f\"🔎 Vector DB created with {index.ntotal} entries.\")\n",
    "\n",
    "# Save FAISS index and data\n",
    "faiss.write_index(index, \"vector_index.faiss\")\n",
    "with open(\"vector_data.pkl\", \"wb\") as f:\n",
    "    pickle.dump(df, f)\n",
    "\n",
    "print(\"✅ Vector index and data saved.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "19894dd4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/prahlad/miniforge/envs/cadquery-env/lib/python3.11/site-packages/torch/nn/modules/module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.\n",
      "  return forward_call(*args, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Prompt: 'Make a circular hole in the center of a rectangular block.'\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.375, -0.703125, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop0=wp_sketch0.moveTo(0.7549342105263157, 0.0).lineTo(0.7549342105263157, 1.40625).lineTo(0.0, 1.40625).lineTo(0.0, 0.0).close()\n",
      "loop1=wp_sketch0.moveTo(0.3700657894736842, 0.7105263157894737).circle(0.11842105263157894)\n",
      "solid0=wp_sketch0.add(loop0).add(loop1).extrude(0.75)\n",
      "solid=solid0\n",
      "\n",
      "Prompt: \"Create a rectangular block with an embedded circular hole.\"\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.390625, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop0=wp_sketch0.moveTo(0.0, -0.3).lineTo(0.75, -0.3).lineTo(0.75, 0.0).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.75)\n",
      "solid=solid0\n",
      "# Generating a workplane for sketch 1\n",
      "wp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.2265625, -0.375, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop1=wp_sketch1.moveTo(0.22894736842105262, 0.0).circle(0.22894736842105262)\n",
      "solid1=wp_sketch1.add(loop1).extrude(-0.296875)\n",
      "solid=solid.cut(solid1)\n",
      "\n",
      "Prompt: \"Create a simple block with rounded edges and then add two smaller circles at specific positions.\"\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, -0.5859375, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop0=wp_sketch0.moveTo(1.4609375, 0.0).lineTo(1.4609375, 0.9688322368421052).lineTo(0.0, 0.9688322368421052).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.3671875)\n",
      "solid=solid0\n",
      "# Generating a workplane for sketch 1\n",
      "wp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.4609375, -0.078125, 0.3671875), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop1=wp_sketch1.moveTo(0.4697368421052631, 0.0).circle(0.4697368421052631)\n",
      "solid1=wp_sketch1.add(loop1).extrude(0.3671875)\n",
      "solid=solid.union(solid1)\n",
      "# Generating a workplane for sketch 2\n",
      "wp_sketch2 = cq.Workplane(cq.Plane(cq.Vector(-0.3046875, -0.078125, 0.7421875), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop2=wp_sketch2.moveTo(0.30394736842105263, 0.0).circle(0.30394736842105263)\n",
      "solid2=wp_sketch2.add(loop2).extrude(-0.3671875)\n",
      "solid=solid.cut(solid2)\n",
      "\n",
      "Prompt: Design a small, rectangular block with a circular cutout in the center and add some rounded corners.\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.2890625, 0.0, -0.109375), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop0=wp_sketch0.moveTo(1.0390625, 0.0).lineTo(1.0390625, 0.24062499999999998).lineTo(0.0, 0.24062499999999998).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.140625)\n",
      "solid=solid0\n",
      "# Generating a workplane for sketch 1\n",
      "wp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.2890625, -0.1015625, 0.0078125), cq.Vector(3.749399456654644e-33, 1.0, -6.123233995736766e-17), cq.Vector(1.0, 0.0, 6.123233995736766e-17)))\n",
      "loop1=wp_sketch1.moveTo(0.035526315789473684, 0.0).circle(0.035526315789473684)\n",
      "solid1=wp_sketch1.add(loop1).extrude(-0.2578125)\n",
      "solid=solid.cut(solid1)\n",
      "\n",
      "Prompt: \"Design a rectangular block with a circular hole at one end and extrude the result.\"\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, 0.0), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop0=wp_sketch0.moveTo(0.75, 0.0).lineTo(0.75, 0.75).lineTo(0.0, 0.75).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.1875)\n",
      "solid=solid0\n",
      "# Generating a workplane for sketch 1\n",
      "wp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(0.296875, -0.1875, 0.375), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop1=wp_sketch1.moveTo(0.07500000000000001, 0.0).circle(0.07500000000000001)\n",
      "solid1=wp_sketch1.add(loop1).extrude(0.296875)\n",
      "solid=solid.union(solid1)\n",
      "\n",
      "Prompt: \"Design a simple rectangular block with an offset circular cutout at the bottom and another hole in the side.\"\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop0=wp_sketch0.moveTo(0.49736842105263157, 0.0).lineTo(0.49736842105263157, 0.75).lineTo(0.0, 0.75).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.296875)\n",
      "solid=solid0\n",
      "# Generating a workplane for sketch 1\n",
      "wp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(0.0, 0.0, 0.296875), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop1=wp_sketch1.moveTo(0.15, 0.0).lineTo(0.15, 0.75).lineTo(0.0, 0.75).lineTo(0.0, 0.0).close()\n",
      "solid1=wp_sketch1.add(loop1).extrude(-0.1484375)\n",
      "solid=solid.cut(solid1)\n",
      "# Generating a workplane for sketch 2\n",
      "wp_sketch2 = cq.Workplane(cq.Plane(cq.Vector(0.2265625, 0.375, 0.296875), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop2=wp_sketch2.moveTo(0.10263157894736843, 0.0).circle(0.10263157894736843)\n",
      "solid2=wp_sketch2.add(loop2).extrude(-1.0)\n",
      "solid=solid.cut(solid2)\n",
      "\n",
      "Prompt: \"Create a stepped and tapered block with an additional circular hole at one end.\"\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, 0.140625), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop0=wp_sketch0.moveTo(0.24868421052631579, 0.0).lineTo(0.24868421052631579, 0.375).lineTo(0.0, 0.375).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.5)\n",
      "solid=solid0\n",
      "# Generating a workplane for sketch 1\n",
      "wp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.75, 0.0, -0.234375), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop1=wp_sketch1.moveTo(0.24868421052631579, 0.0).lineTo(0.24868421052631579, 0.375).lineTo(0.0, 0.375).lineTo(0.0, 0.0).close()\n",
      "solid1=wp_sketch1.add(loop1).extrude(0.328125)\n",
      "solid=solid.union(solid1)\n",
      "# Generating a workplane for sketch 2\n",
      "wp_sketch2 = cq.Workplane(cq.Plane(cq.Vector(-0.5, 0.0, -0.234375), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop2=wp_sketch2.moveTo(1.0329769736842105, 0.0).lineTo(1.0329769736842105, 0.496875).lineTo(1.2421875, 0.496875).lineTo(1.2421875, 0.7453125).lineTo(0.496875, 0.7453125).lineTo(0.0, 0.7453125).lineTo(0.0, 0.3661184210526316).lineTo(0.0, 0.0).close()\n",
      "loop3=wp_sketch2.moveTo(0.496875, 0.3661184210526316).circle(0.14383223684210528)\n",
      "solid2=wp_sketch2.add(loop2).add(loop3).extrude(0.25)\n",
      "solid=solid.union(solid2)\n",
      "\n",
      "Prompt: \"Design a rectangular block with four circular holes cut out from the sides.\"\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.75, -0.3046875, 0.0), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop0=wp_sketch0.moveTo(1.5, 0.0).lineTo(1.5, 0.6).lineTo(0.0, 0.6).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.6015625)\n",
      "solid=solid0\n",
      "# Generating a workplane for sketch 1\n",
      "wp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(-0.0859375, -0.3046875, 0.3046875), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop1=wp_sketch1.moveTo(0.08684210526315789, 0.0).circle(0.08684210526315789)\n",
      "solid1=wp_sketch1.add(loop1).extrude(-0.6015625)\n",
      "solid=solid.cut(solid1)\n",
      "# Generating a workplane for sketch 2\n",
      "wp_sketch2 = cq.Workplane(cq.Plane(cq.Vector(-0.4453125, -0.3046875, 0.3046875), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop2=wp_sketch2.moveTo(0.08684210526315789, 0.0).circle(0.08684210526315789)\n",
      "solid2=wp_sketch2.add(loop2).extrude(-0.6015625)\n",
      "solid=solid.cut(solid2)\n",
      "# Generating a workplane for sketch 3\n",
      "wp_sketch3 = cq.Workplane(cq.Plane(cq.Vector(0.28125, -0.3046875, 0.3046875), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop3=wp_sketch3.moveTo(0.08684210526315789, 0.0).circle(0.08684210526315789)\n",
      "solid3=wp_sketch3.add(loop3).extrude(-0.6015625)\n",
      "solid=solid.cut(solid3)\n",
      "# Generating a workplane for sketch 4\n",
      "wp_sketch4 = cq.Workplane(cq.Plane(cq.Vector(-0.703125, -0.2578125, 0.6015625), cq.Vector(1.0, 0.0, 0.0), cq.Vector(0.0, 0.0, 1.0)))\n",
      "loop4=wp_sketch4.moveTo(1.40625, 0.0).lineTo(1.40625, 0.5625).lineTo(0.0, 0.5625).lineTo(0.0, 0.0).close()\n",
      "solid4=wp_sketch4.add(loop4).extrude(-0.5546875)\n",
      "solid=solid.cut(solid4)\n",
      "\n",
      "Prompt: Create a stepped block with a circle at the top.\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.5546875, 0.0, -0.0625), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop0=wp_sketch0.moveTo(0.05838815789473684, 0.0).lineTo(0.05838815789473684, -0.08174342105263158).lineTo(0.1401315789473684, -0.08174342105263158).lineTo(0.1401315789473684, 0.0).lineTo(1.109375, 0.0).lineTo(1.109375, 0.12845394736842106).lineTo(0.1401315789473684, 0.12845394736842106).lineTo(0.1401315789473684, 0.33865131578947366).lineTo(0.05838815789473684, 0.33865131578947366).lineTo(0.05838815789473684, 0.12845394736842106).lineTo(0.0, 0.12845394736842106).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.75)\n",
      "solid=solid0\n",
      "# Generating a workplane for sketch 1\n",
      "wp_sketch1 = cq.Workplane(cq.Plane(cq.Vector(0.578125, -0.4609375, 0.0), cq.Vector(-0.049067674327418015, 0.9987954562051724, -6.123233995736766e-17), cq.Vector(0.9987954562051724, 0.049067674327418015, 6.123233995736766e-17)))\n",
      "loop1=wp_sketch1.moveTo(0.06315789473684211, 0.0).circle(0.06315789473684211)\n",
      "solid1=wp_sketch1.add(loop1).extrude(-1.0)\n",
      "solid=solid.cut(solid1)\n",
      "\n",
      "Prompt: \"Create a simple circular shape and extrude it to form a small block.\"\n",
      "Code:\n",
      "import cadquery as cq\n",
      "# Generating a workplane for sketch 0\n",
      "wp_sketch0 = cq.Workplane(cq.Plane(cq.Vector(-0.234375, 0.0, -0.75), cq.Vector(1.0, 6.123233995736766e-17, -6.123233995736766e-17), cq.Vector(6.123233995736766e-17, -1.0, 6.123233995736766e-17)))\n",
      "loop0=wp_sketch0.moveTo(0.04736842105263158, 0.04736842105263158).lineTo(0.04736842105263158, 1.4526315789473685).lineTo(0.0, 1.5).lineTo(0.0, 0.0).close()\n",
      "solid0=wp_sketch0.add(loop0).extrude(0.0546875, both=True)\n",
      "solid=solid0\n"
     ]
    }
   ],
   "source": [
    "import faiss\n",
    "import pickle\n",
    "from sentence_transformers import SentenceTransformer\n",
    "\n",
    "# Load index and data\n",
    "index = faiss.read_index(\"vector_index.faiss\")\n",
    "with open(\"vector_data.pkl\", \"rb\") as f:\n",
    "    df = pickle.load(f)\n",
    "\n",
    "# Load model\n",
    "model = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
    "\n",
    "# Query\n",
    "query = \"circular block\"\n",
    "query_embedding = model.encode([query]).astype(\"float32\")\n",
    "\n",
    "# Search top 5 results\n",
    "D, I = index.search(query_embedding, k=10)\n",
    "for idx in I[0]:\n",
    "    print(f\"\\nPrompt: {df.iloc[idx]['prompt']}\\nCode:\\n{df.iloc[idx]['code']}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "10e2a35f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: faiss-cpu in /Users/prahlad/miniforge/envs/cadquery-env/lib/python3.11/site-packages (1.11.0.post1)\n",
      "Collecting pandas\n",
      "  Downloading pandas-2.3.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (91 kB)\n",
      "Requirement already satisfied: numpy<3.0,>=1.25.0 in /Users/prahlad/miniforge/envs/cadquery-env/lib/python3.11/site-packages (from faiss-cpu) (1.26.4)\n",
      "Requirement already satisfied: packaging in /Users/prahlad/miniforge/envs/cadquery-env/lib/python3.11/site-packages (from faiss-cpu) (24.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Users/prahlad/miniforge/envs/cadquery-env/lib/python3.11/site-packages (from pandas) (2.9.0.post0)\n",
      "Collecting pytz>=2020.1 (from pandas)\n",
      "  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)\n",
      "Collecting tzdata>=2022.7 (from pandas)\n",
      "  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)\n",
      "Requirement already satisfied: six>=1.5 in /Users/prahlad/miniforge/envs/cadquery-env/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Downloading pandas-2.3.1-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.8/10.8 MB\u001b[0m \u001b[31m1.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0mm\n",
      "\u001b[?25hUsing cached pytz-2025.2-py2.py3-none-any.whl (509 kB)\n",
      "Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)\n",
      "Installing collected packages: pytz, tzdata, pandas\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3/3\u001b[0m [pandas]2m2/3\u001b[0m [pandas]\n",
      "\u001b[1A\u001b[2KSuccessfully installed pandas-2.3.1 pytz-2025.2 tzdata-2025.2\n"
     ]
    }
   ],
   "source": [
    "!pip install faiss-cpu pandas\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
